config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resource :period_accuracies, only: [:new, :create]
  resource :weekly_rankings, only: [:new, :create]
end

app/models/answer.rb
class Answer < ApplicationRecord
  scope :correct, -> { where(correct: true) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/period_accuracy.rb
class PeriodAccuracy
  include ActiveModel::Model
  attr_accessor :name, :start_date,  :end_date
end

app/models/user.rb
class User < ApplicationRecord
  has_many :answers
  def corrected_percentage(start_date, end_date)
    answers = self.answers.where("created_at  BETWEEN ? AND ?", start_date, end_date)
    (100.0 * answers.correct.count / answers.count ).round
  end
end

app/models/weekly_ranking.rb
class WeeklyRanking
  include ActiveModel::Model
  attr_accessor :start_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/period_accuracies_controller.rb
class PeriodAccuraciesController < ApplicationController
  def new
    @period_accuracy = PeriodAccuracy.new
  end
  def create
    @user = User.find_by(name: params[:period_accuracy][:name])
    Time.use_zone(@user.timezone) do
      @start_date = Time.zone.parse(params[:period_accuracy][:start_date].to_s)
      @end_date = Time.zone.parse(params[:period_accuracy][:end_date].to_s)
    end
    @answers = @user.answers
    @answers_in_period = @answers.where("created_at  BETWEEN ? AND ?", @start_date, @end_date)
    @correct = @answers.correct
    @correct_in_period = @correct.where("created_at  BETWEEN ? AND ?", @start_date, @end_date)
    @percentage_total = 100.0 * @correct.count / @answers.count
    @percentage__in_period = if @answers_in_period
                                100.0 * @correct_in_period.count / @answers_in_period.count
                             else
                                 'No answers'
                             end    
  end
end

app/controllers/weekly_rankings_controller.rb
class WeeklyRankingsController < ApplicationController
  def new
    @weekly_ranking = WeeklyRanking.new
  end
  def create
    @start_date = params[:weekly_ranking][:start_date].to_date.beginning_of_week
    @start_date_time = Time.zone.parse(@start_date.to_s).utc
    @end_date = params[:weekly_ranking][:start_date].to_date.end_of_week + 1
    @end_date_time = Time.zone.parse(@end_date.to_s).utc
    @prev_start_date = @start_date - 7
    @prev_start_date_time = Time.zone.parse(@prev_start_date.to_s).utc
    @prev_end_date = @end_date - 7
    @prev_end_date_time = Time.zone.parse(@prev_end_date.to_s).utc
    @users = User.all.sort_by{|user| user.corrected_percentage(@start_date_time, @end_date_time)}.first(100)
    @ids = User.all.sort_by{|user| user.corrected_percentage(@prev_start_date_time, @prev_end_date_time)}.map(&:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% if flash.any? %>
  <div class="app-flash">
    <% flash.each do |type, body| %>
      <%# only render the usual messages %>
      <% next unless %w(success notice error info).include?(type.to_s) %>

      <%= content_tag :div, class: "alert alert-#{type} alert-flash" do %>
        <div class="container">

          <div class="media">
            <%= icon_svg("alerts/#{type}.svg", class: "d-flex mr-3 icon icon-3x") %>
            <div class="media-body">
              <%= content_tag(:h6, t(".headline.#{type}"), class: "text-uppercase text-reset my-1") %>
              <% if body.kind_of?(Array) %>
                <ul class="mb-0">
                  <% body.each do |message| %>
                    <%= content_tag(:li, message) %>
                  <% end %>
                </ul>
              <% else %>
                <p class="mb-0"><%= body %></p>
              <% end %>
            </div>
          </div>

        </div>
      <% end if body.present? %>
    <% end %>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="app-footer text-center">
  <div class="container">
    <p>Copyright 2009-<%= Time.now.year %> <a href="https://membean.com">Membean</a></p>
    <ul class="footer-links">
      <li><a href="https://membean.com/privacy">Privacy Policy</a></li>
      <li class="muted">·</li>
      <li><a href="https://membean.com/agreement">Terms of Service</a></li>
    </ul>
  </div>
</footer>

app/views/application/_header.html.erb
<div class="app-header">
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Memseed", '#', class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar-header">
        <ul class="navbar-nav ml-auto">
          <%= content_tag(:li, link_to("Area1", new_period_accuracies_path, class: "nav-link"), class: "nav-item") %>
          <%= content_tag(:li, link_to("Area2", new_weekly_rankings_path, class: "nav-link"), class: "nav-item") %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/home/index.html.haml
= 'Your application here'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Code challenge</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
</head>
<%= content_tag :body, data: { action: action_name, controller: controller_name, path: request.path } do %>
  <%= render "header" %>

  <div class="app-example-overview bg-light py-5">
    <div class="container">
      <div class="row justify-content-center">
          <%= render "flash" %>
          <%= yield %>
      </div>
    </div>
  </div>

  <%= render "footer" %>
  <%= javascript_include_tag "application" %>
<% end %>
</html>

app/views/period_accuracies/create.html.haml
= @user.name
= @percentage_total
= @percentage__in_period

app/views/period_accuracies/new.html.haml
= form_for @period_accuracy do |f|
  = f.text_field :name
  = f.date_field :start_date
  = f.date_field :end_date
  = f.submit "Create"

app/views/weekly_rankings/create.html.haml
= @start_date
= @start_date_time
= @end_date
= @end_date_time
%br/
-@users.each_with_index do |user, i|
  = i
  = user.name
  = @ids.index(user.id) - i
  %br/

app/views/weekly_rankings/new.html.haml
= form_for @weekly_ranking do |f|
  = f.date_field :start_date
  = f.submit "Create"